### PR TITLE
Recommend fix

### PR DESCRIPTION
**Pull request by LeCleric**
Improved the algorithm and fixed it so that it displays suggestions even when there is no data for it to draw from the user's subscriptions.

#79 #90

### CODE REVIEW

**Comment by ghost** [comment]
Is it normal that now in the Discovery page, it only shows the lastest added podcast for "Similar to" ?

Eg. I added the podcast "Daily news" and "Oprah"; but its only showing "Similar to: Oprah"

**Comment by FrankSauve** [comment]
@Raph1105 It selects a random podcast from the ones you are subscribed to

**Comment by Raph1105** [comment]
For me, it only takes the latest one..

**Comment by ghost** [comment]
Nevermind, it's good :)

**Review by ghost — APPROVED** [review]

**Review by FrankSauve — APPROVED** [review]

**Pull request merged**
