### PR TITLE
Folders tab

### PR DESCRIPTION
**Pull request by Cotso**
Renaming, and deleting from side menu, and tests still need to be done.

### CODE REVIEW

**Review by FrankSauve — CHANGES_REQUESTED** [review]
There seems to be a missing semi-colon
image

**Comment by FrankSauve** [comment]
There's a lot of compilation errors here
@Cotso Did you run the code on your machine before pushing?
image

**Comment by FrankSauve** [comment]
There is still compilation errors
image

**Comment by FrankSauve** [comment]
I fixed the compilation error, but I'm very confused by this pull request...
The "My folders" tab isn't there at all and there doesn't seem to be any added feature.
@Cotso Can you explain how this is supposed to work
image

**Comment by Cotso** [comment]
It's not finished, but I had a hard time figuring out how to add the folders to the already implemented list view.  There should be two list views there splitting the drawer by weight.  The top list view is the normal one and takes up 2/3rds of the drawer which is why the folders tab isn't seen there.  It is scrollable though.  The blank 1/3rd at the bottom is a separate list view that's populated by folders.  I understand it's not the best way to handle it.  Suggestions are always welcome.

**Comment by FrankSauve** [comment]
When I click on a folder the podcasts inside it never show up
image

**Pull request closed without merging**
