### PR TITLE
Advanced search

### PR DESCRIPTION
**Pull request by williamkingbede**
Podcasts can be searched by category, language, title and Artist name in iTunes search page.

References:
[https://github.com/FrankSauve/390AntennaPod/wiki/Itunes-API-Reference](https://github.com/FrankSauve/390AntennaPod/wiki/Itunes-API-Reference)

### CODE REVIEW

**Comment by williamkingbede** [comment]
#33 #49

**Review by LeCleric — COMMENTED** [review]
Is it normal that there is no longer an option for a standard search?
image

**Comment by williamkingbede** [comment]
I removed it cause it was no longer useful but I can add it back if needed

**Comment by LeCleric** [comment]
Yeah, I just feel like an average user who wants to do a normal search wouldn't think to press the three dot icon followed by title instead of just a magnifying glass

**Comment by FrankSauve** [comment]
Yeah I agree with @LeCleric , normal search should be there

**Comment by williamkingbede** [comment]
Alright going to add it back and push

**Comment by LeCleric** [comment]
I found a small error, selecting the title search from the dropdown, then selecting the artist search from the dropdown has the searches overlay on top of one another and stay on every page. Standard search doesn't have that though.

image

image

**Comment by williamkingbede** [comment]
Yea I got this too I don't know how to fix this.. For now we have to press the back arrow before doing another search.

**Comment by LeCleric** [comment]
Okay, guess we can Merge this and just make an issue outlining this to fix it later?

**Comment by williamkingbede** [comment]
Yes we can do that. Another thing that I'm fixing now is that when the search query starts with an Uppercase, iTunes returns objects that are not podcasts. Strange..

**Review by LeCleric — APPROVED** [review]

**Review by FrankSauve — APPROVED** [review]

**Pull request merged**
