### PR TITLE
Subcategories

### PR DESCRIPTION
**Pull request by FrankSauve**
Added subcategories to the advanced search menu.
Includes unit test.

Not implemented exactly like the mockup.

#53 #54

### CODE REVIEW

**Review by LeCleric — APPROVED** [review]

**Comment by williamkingbede** [comment]
Small thing but when clicking on a category or subcategory the top title changes accordingly which is good but when I select directly after a language the top title still the same so I think it would better for consistency if the title is changed back to 'Add Podcast' or we could even put the Language selected as title.

**Comment by FrankSauve** [comment]
Good point we should put the language as the title

**Comment by LeCleric** [comment]
Alright, I'm on it. Should be really quick.

**Comment by williamkingbede** [comment]
Alright should be good now

**Review by williamkingbede — APPROVED** [review]

**Pull request merged**
