### PR TITLE
Autocomplete for title search and artist search

### PR DESCRIPTION
**Pull request by FrankSauve**
Includes unit tests #67 #68 

TODO:
- [ ] Remove duplicates in artists search

### CODE REVIEW

**Review by LeCleric — COMMENTED** [review]
Unit tests worked.
The actual functionality didn't work, but then started working. 
Then my computer completely froze. This was likely a problem specific to my terrible computer. I'll try running it again tonight.

**Review by LeCleric — APPROVED** [review]

**Comment by ghost** [comment]
It's making the app crash on my computer :/..

**Comment by FrankSauve** [comment]
That's weird it works fine for me

**Comment by ghost** [comment]
Now, it's  working.. but the first time it did not work. 
Yes .. it's kind of weird.

**Review by ghost — APPROVED** [review]

**Pull request merged**
