### PR TITLE
Discovery page

### PR DESCRIPTION
**Pull request by ghost**
Discovery page was added as well as its tab in the menue and the icon

### CODE REVIEW

**Comment by ghost** [comment]
#44

**Comment by ghost** [comment]
#43

**Comment by ghost** [comment]
Done with Discovery page --> only missing the unit tests and the ui test for the settings page !

**Comment by FrankSauve** [comment]
Awesome work! Just a few things that should be fixed:

- ~~When you change the discovery preferences, you need to go to another tab and back to the discovery tab for the podcasts to reload. It would be better if it was reloaded when the user clicks on confirm.~~ (Added in commit 5258bc4)

- Selecting more than one category preference only loads the first one instead of loading all the checked preferences. It can probably be fixed by changing updateDate() to appendData()

**Comment by ghost** [comment]
Thank you !
I'll fix it all !

**Comment by FrankSauve** [comment]
Nevermind the first point, it reloads when you click confirm.

**Comment by ghost** [comment]
@FrankSauve the second point should be fixed with my last commit. (d2faa66)

**Review by FrankSauve — APPROVED** [review]
Works perfectly

**Review by LeCleric — APPROVED** [review]

**Comment by ghost** [comment]
TODO: remove Discovery Adapter --> useless

**Pull request merged**
